name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: [head, 3.2, 3.1, 3.0, 2.7, 2.5]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test
